### ISSUE TITLE
identify_gaps()

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#13]
Given a multi-level network, 
- specify a type of gap (eg. an open four-circle across levels) 
a ------- b
|              |
c  (gap)  d
- find and rank potential ties between nodes on one level that would close the largest number of such gaps
- return these potential ties (given a threshold probably)

**Comment by marioangst** [comment]
sma$isClosedMotifR is currently not yet included in sma as installed through pip @tseppelt

**Comment by tseppelt** [comment]
The function is included in sma 2.0.5. Call
```R
py_install("sma", pip =TRUE)
```
to update. I will include the missing features and bug fixes in the next version 2.0.6.

**Comment by marioangst** [comment]
Perfect!
