### ISSUE TITLE
consistent, general name for level attribute

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#22]
given "lvl" is used in tidygraph notation for multilevel networks and the package is more generally applicable than to SES networks, I would suggest:
- renaming type_attr to lvl_attr
- sesType to lvl

**Comment by tseppelt** [comment]
This should be easy on the R side. I think it is not necessary to do this in Python right now.

**Comment by marioangst** [comment]
ok, I will do it then - just wanted to check if there would be trouble on the Python side

**Comment by marioangst** [comment]
resolved in bf00ab83991e56dd1ddc3d08f17470cfb6277378
