### ISSUE TITLE
Documentation of function parameters for random baseline

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#25]
I had a user contacting me who wanted to estimate a model based on actors_choice, but could not find info on
- how to set the parameter
- how to set the "fixed" level
I looked through things and noticed we have to streamline documentation on this in the three functions related to baselines.
Further, specifying the fixed level needs to be possible/ documented better.

**Comment by tseppelt** [comment]
@marioangst I have added explanations to the vignette and to the functions involved. I think I didn't manage to re-build the online documentation though.

**Comment by marioangst** [comment]
I rebuilt the website and added some further documentation in dd8c7f81dd7849dabaeb5390f7fab4c45f791637
