### ISSUE TITLE
actors_choice model type for simulation, variance for 2,2 motifs

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#26]
related to #25 
not urgent, maybe something to consider for the next version.

**Comment by tseppelt** [comment]
2e2e781 adds actors_choice for simulation, this requires sma>=2.0.7 now available on PyPI

**Comment by tseppelt** [comment]
sma>=2.0.8 includes variances for 4-motifs in Erdos-Renyi. Update from PyPI using
```r
py_install("sma", pip = TRUE)
```

**Comment by tseppelt** [comment]
There were some flaws in the formulas for the variances of 4-motifs. They were taken care of in sma 2.0.10. Please update using
```r
py_install("sma", pip = TRUE)
```
