### ISSUE TITLE
Move pkgdown page generation to Travis CI

### ISSUE THREAD

**Issue by tseppelt** [marioangst/motifr#28]
Currently, after every update ``pkgdown::build_site()`` has to be called manually in order to update the motifr webpage. This can be automatized following [this manual](https://www.datacamp.com/community/tutorials/cd-package-docs-pkgdown-travis).

@marioangst please link the repository to Travis CI. I'll do the necessary changes.

**Comment by marioangst** [comment]
@tseppelt repository linked, yaml updated e04a2e895caec66f7ffcb62f1dbaef5e29d0c469

**Comment by marioangst** [comment]
travis has some trouble with the magick package (to be expected, it's based on imagemagick outside R)

**Comment by marioangst** [comment]
have to run but this might be a solution: https://travis-ci.community/t/error-configuration-failed-for-package-magick/1674/2

**Comment by marioangst** [comment]
if magick makes problems, we could also discard it (it is used in show_3motifs and show_4motifs, which we can also implement without relying on static images)
