### ISSUE TITLE
Vignette update on comparing multiple baseline models

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#35]
Preferable to implementing this in a function - illustrate how user can do himself and suggest how to graph it.

**Comment by marioangst** [comment]
Would require adding additional packages to nicely to, so we will leave it to the user.

**Comment by tseppelt** [comment]
@marioangst what about [ggplot2::multiplot](http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_(ggplot2)/)?
