### ISSUE TITLE
ml_net is directed

### ISSUE THREAD

**Issue by tseppelt** [marioangst/motifr#38]
Surprisingly,
```r
> is.directed(ml_net)
[1] TRUE
```
I think ``m̀l_net`` shouldn't be directed. Please check.

**Comment by tseppelt** [comment]
c75eb16 added support for directed networks. Now, with default parameters, ``ml_net`` is treated as directed network which hence exhibits only directed motifs. This has the consequence that most examples in the vignettes don't work anymore as there based on undirected motifs. Two solutions:

- either treat ``ml_net`` as undirected network by setting ``directed = FALSE`` where appropriate
- or add another real-world example network, which is undirected, and rewrite the vignettes.

@marioangst how shall we handle this? You know ``ml_net`` best.

**Comment by marioangst** [comment]
symmetrized the network - for illustrative reasons, this works well.

**Comment by marioangst** [comment]
made undirected, ok for illustrative purposes here. a59f280e4382d617cf8c7d3c5770aa836e8dfe83
#
