### ISSUE TITLE
Directed motifs

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#39]
Would be quite nice...

**Comment by marioangst** [comment]
zoo nomenclature might make trouble though

**Comment by tseppelt** [comment]
This should be possible with only minor alterations. @marioangst, could you provide a list of the motifs that ought to be supported?

**Comment by tseppelt** [comment]
With the latest sma update (2.0.11) and c75eb16, two types of directed motifs are supported: signatures 1,1 and 2, see [the motif zoo](https://gitlab.com/t.seppelt/sesmotifanalyser/raw/master/doc/_build/latex/SESMotifAnalyser.pdf?inline=false).

**Comment by marioangst** [comment]
Hmm vielleicht so. Für 1,2 Motifs mit a auf Level 1 und b1 und b2 auf Level 2
Wenn ich mir Anwendungsfelder vorstelle kommts eigentlich nur auf geschlossene und offene Triangles an. Vorschlag für Nomenklatur basierend auf der undirected:

1,2[I.C.1]: a->b1, a->b2
1,2[I.C.3]: a<->b1, a->b2
1,2[I.C.4]: a<->b1, a<->b2

1,2[II.C.1]: a->b1, a->b2, b1->b2
1,2[II.C.2]: a->b1, a->b2, b1<->b2
1,2[II.C.3]: a<->b1, a<->b2, b1->b2
1,2[II.C.4]: a<->b1, a<->b2, b1<->b2

1,2[II.B.1]: a->b1, b1->b2
1,2[II.B.2]: a->b1, b1<-b2
1,2[II.B.3]: a->b1, b1<->b2
1,2[II.B.4]: a<->b1, b1<->b2
1,2[II.B.5]: a<->b1, b1->b2
1,2[II.B.6]: a<->b1, b1<-b2

**Comment by tseppelt** [comment]
I've implemented directed (1,2)-motif. Update sma to version 2.1.0 and check [the docs](https://gitlab.com/t.seppelt/sesmotifanalyser/raw/master/doc/_build/latex/SESMotifAnalyser.pdf?inline=false).
