### ISSUE TITLE
remove dependence of show_3_motifs and show_4_motifs on static images

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#41]
instead generate from show_motif

**Comment by marioangst** [comment]
have a version for directed and undirected

**Comment by tseppelt** [comment]
@marioangst Have a look at the two new functions https://marioangst.github.io/motifr/reference/supported_signatures.html and https://marioangst.github.io/motifr/reference/supported_classes.html (about to appear: d4f1a74). Maybe this helps.

**Comment by marioangst** [comment]
That is very helpful. I am going to delete the show_3_motifs and show_4_motifs. I have a more interactive idea in mind, let's see.

**Comment by marioangst** [comment]
Moved over to shiny app #43
