### ISSUE TITLE
Motif zoo shiny app

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#43]
Make a Shiny app to explore the Motif zoo:

Some reference
https://deanattali.com/2015/04/21/r-package-shiny-app/

That is very helpful. I am going to delete the show_3_motifs and show_4_motifs. I have a more interactive idea in mind, let's see.

_Originally posted by @marioangst in https://github.com/marioangst/motifr/issues/41#issuecomment-696130876_

**Comment by marioangst** [comment]
There now is a shiny app to explore the zoo. Thanks a lot @tseppelt for the supported_classes and supported_signatures, made it a breeze to make one quickly.

**Comment by marioangst** [comment]
The app can be launched with explore_zoo()

**Comment by tseppelt** [comment]
@marioangst The app looks amazing! I noticed a problem with directed motif classes. Somehow the app didn't want to show me classes for directed motifs.

In order to avoid confusion I've decided to make the ``directed`` parameter in ``supported_classes()`` mandatory. Could you update the app accordingly?

**Comment by marioangst** [comment]
note to self: also make it possible to pass user network object
could get messy but might work: https://stackoverflow.com/questions/44999615/passing-parameters-into-shiny-server/48831832#48831832

**Comment by marioangst** [comment]
as of f91fa1d797af57b4d19c79e99d38a0f5cd6f0b45 the user can now supply their own network to the app

**Comment by marioangst** [comment]
as of fa258a7467c8ee28e1b47c746b858df5e08b15ba directed motifs are shown
