### ISSUE TITLE
ergm as baseline only on single level

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#46]
In terms of use cases for having an ergm as a baseline, most people would probably want to have it at one level of the network only. Especially because fitting multi-level ergms with actual multi-level parameters is currently a bit tricky. 

As such, we would need to have something like a combination of actors_choice and ergm. @tseppelt doable?

**Comment by tseppelt** [comment]
@marioangst I've added an implementation for ergms on a single level. (Working with the network package is always a bit messy…). When re-writing the baseline vignette, you can use the example that I've quickly added to the bottom of it. It illustrates the workflow that I had in mind.
