### ISSUE TITLE
explicit return if motif cannot be found

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#50]
We should have a return (it would make sense if this was returned from sma) if a motif cannot be found in a given network.

This would make for a much better UI in show_motif and explore_motifs, because we could then throw an explicit error message (eg. "the motif(s) xxx do not exist in the network supplied")

**Comment by tseppelt** [comment]
With the next version of sma (2.1.2, currently being uploaded to PyPI), 
exemplify_motif will return NULL instead of raising an error:

```r

 > exemplify_motif(directed_dummy_net, "2,1[III.C.6]")
NULL
```

**Comment by marioangst** [comment]
wrapped up in 400400b0940e7b8243adf65dafd32714a2647d79
