### ISSUE TITLE
Motifs 2,2[III.B] and 2,2[III.C]

### ISSUE THREAD

**Issue by meefen** [marioangst/motifr#59]
I am a little confused by how the layers are handled in these motifs. 

For instance, according to the SESMotifAnalyser Documentation, in `2,2[III.B]` two actors are connected while two resources are not connected; and `2,2[III.C]` vice versa. 

But when you run the following code, you get the opposite: in `2,2[III.C]` two actors are connected while two resources are not connected; and `2,2[III.B]` vice versa. 

```
show_motif("2,2[III.B]", net = ml_net, directed = FALSE, label = TRUE)
show_motif("2,2[III.C]", net = ml_net, directed = FALSE, label = TRUE)
```

Is this by design, or a bug? Please let me know if I've misinterpreted anything.

**Comment by meefen** [comment]
More testing code below and the results does not seem to align with the SESMotifAnalyser Documentation. Please kindly advise.

```
plot_sesMotif_guide <- function(network, title) {
  par(mfrow=c(7, 4))
  rows <- as.roman(1:7) %>% as.character()
  columns <- c("A", "B", "C", "D")
  for(row_class in rows) {
    for (col in columns) {
      motif_name <- paste0("2,2[", row_class, ".", col, "]")
      plot(show_motif(motif = motif_name, net = network, label = TRUE, directed = FALSE),
           main = motif_name)
    }
  }
}

plot_sesMotif_guide(ml_net, "ml_net")
```

**Comment by marioangst** [comment]
Hi @meefen thanks for the super nice issue description. I would hand this over to @tseppelt in a first pass, @tseppelt can you check if this is an issue of SESMotifAnalyser Documentation or if it's actually a wrong translation?

**Comment by tseppelt** [comment]
Hi @meefen, thank you for bringing up this issue! I think this is not a bug but rather a problem with the slightly cumbersome description of the intended behavior of our package.

In ``ml_net``, the zeroth level is the "ecological" level (SpatPlanA etc.) while the first level is the level of the actors. When you call 
```r
show_motif("2,2[III.B]", net = ml_net, directed = FALSE, label = TRUE)
```
the ecological level is associated with the first level of the (2,2)-motifs, while the actor level is associated with the second level. Here one has to be careful. In [the figure](https://gitlab.com/t.seppelt/sesmotifanalyser/-/raw/master/doc/_static/fourMotifs.pdf?inline=false), the first level is indicated with red nodes and the second level with green nodes. So the ecological nodes like SpatPlanA in ``ml_net`` are treated as red node and the actors as green nodes. If you want the opposite behavior, call
```r
show_motif("2:1,2:0[III.B]", net = ml_net, directed = FALSE, label = TRUE)
```
as described in [the manual](https://marioangst.github.io/motifr/articles/motif_zoo.html). This overrides the automatic position matching and assigns the color green to the level zero and color red to level one. I hope this answers your question. I have also added a warning to the documentation of sma.

P.S.: Have you tried using ``explore_motifs()``, the interactive guide through the motif zoo?

**Comment by meefen** [comment]
@tseppelt Thank you for the help! The precise position matching solved my problem.

I was indeed confused by the mismatch between the figure (in Bodin & Tengo) and the motifr result. As a beginner, I see the 0th, 1st, and 2nd levels confusing and hard to grasp. Maybe this difficulty was caused by my entry from the Bodin & Tengo paper. 

Also wondering whether this is a side effect of R and Python's difference in handling the start number (1 vs. 0). 

Thanks again, @tseppelt and @marioangst
