### ISSUE TITLE
2,3 undirected motif

### ISSUE THREAD

**Issue by fedeholm** [marioangst/motifr#66]
Hi! I am working on some multi-layer network processes and I wanted to request the inclusion of a 2-3 motif that might be relevant for many of us out here. Given the importance of brokers or connectors in many social and natural processes, this motif could prove very helpful. I am adding a diagram of the motif in question:

![thumbnail_image001](https://user-images.githubusercontent.com/33849653/179063574-214cfbd1-dcc2-4242-aef3-f82a1fa10da6.png)

Thanks!

**Comment by tseppelt** [comment]
Dear @fedeholm, thank you for your request. I''ve added support for this (2,3)-motif. Please update your installation by calling
```R
motifr::update_motifr()
```
The underlying Python package sma must have version >=2.3.1.

Let us know if you have any further requests.

Best,
Tim

**Comment by fedeholm** [comment]
Dear @tseppelt, thank you for the immediate response! Amazing.

I'll let you know if any other motifs are necessary.

Best,
Fede
