### ISSUE TITLE
wrong counts (-1) in some 3-level motifs

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#68]
@fedeholm got in contact with me about motifr not counting some 3-level (2,2,1) motifs in his dataset (returning -1) in cases where the motif in question can be found in the network.
Not all (2,2,1) motifs are affected.  
- 2,2,1 [I.B.2] works
- 2,2,1 [III.B.2] works

I was able to reduce it down to a reprex and it seems this is actually a bug. The following produces a network only containing the motif in question for 2,2,1[II.C.1]. motifr returns -1. 

```
el <- cbind(
  c(1,1,2,2,3),
  c(4,5,4,5,5)
)
attr <- data.frame(
  names = 1:5,
  level_3 = c(0,0,1,2,1))
test_net <- igraph::graph_from_edgelist(el,directed = FALSE)
test_net <- igraph::set.vertex.attribute(test_net,"level_3",value = attr$level_3)
# motif can be found
motifr::show_motif("2,2,1[II.C.1]",net = test_net,lvl_attr = "level_3",label=TRUE)
# motif is not counted
motifr::count_motifs("2,2,1[II.C.1]",net = test_net,lvl_attr = "level_3")
```

**Comment by marioangst** [comment]
@tseppelt I have explored it for a bit and I cannot get to the root of it. I can replicate it using the newest as well as an older version of sma and also when growing the network beyond one motif.

**Comment by tseppelt** [comment]
@marioangst, thank you for investigating this. The bug was caused by a problem with the ``sma.findIdealCounter`` function which I just resolved. Please update sma to version >=2.3.2.
