### ISSUE TITLE
1,3 undirected motif

### ISSUE THREAD

**Issue by fedeholm** [marioangst/motifr#69]
Hi @marioangst, @tseppelt,

 I wanted to request the inclusion of an additional motif: an undirected 4-motif with signature 1,3 (this seems like a fairly common arrangement, so apologies in advance if I missed it in the vignette):

![Slide1](https://user-images.githubusercontent.com/33849653/194355714-437ca726-fb40-4632-bc55-3bb66d800933.JPG)

Thanks!
Fede

**Comment by tseppelt** [comment]
@fedeholm I've finally found time to work on this. The latest version of sma (2.3.3) comes with support for your (1,3)-motif. Please update sma using ``motifr::update_motifr()`` and try counting motifs of type ``1,3[1]``. I'd much appreciate if you could do some testing and let me know if anything doesn't work as expected.

**Comment by fedeholm** [comment]
Hi Tim,

Thank you! I really appreciate it. I'll be doing some testing and let you
know how things go.
fh.
