### ISSUE TITLE
visualization function based on ggraph

### ISSUE THREAD

**Issue by marioangst** [marioangst/motifr#8]
split viz and offset coordinates - also could consider as a suggestion for ggraph.

**Comment by marioangst** [comment]
arrange plots in circle necessary

**Comment by tseppelt** [comment]
> arrange plots in circle necessary

When arranging n points on a circle, the k-th point, k = 0, …, n-1, has coordinates x = cos(2 \* pi \* k /n) and y = sin(2 \* pi \* k/n). This gives coordinates ranging from -1 to 1. See https://en.wikipedia.org/wiki/Root_of_unity#General_definition

**Comment by marioangst** [comment]
works now :)! 23271e9dfc3defbb4e9eb1f9d334a0d96e28fd20
